### ISSUE TITLE
https://www.swiftdemand.com/?referred_by=ljilja11

### ISSUE THREAD

**Issue by ljilja111** [swiftdemand/swiftprotocol#10]
Pridruzi se jos danas

**Comment by tigor1988** [comment]
oke...

On Feb 25, 2018 21:53, "ljilja111" <notifications@github.com> wrote:

Pridruzi se jos danas

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/swiftdemand/swiftprotocol/issues/10>, or mute the thread
