### ISSUE TITLE
The store doesn’t deliver 

### ISSUE THREAD

**Issue by lucyho** [swiftdemand/swiftprotocol#12]
I have ordered a logo from 2 different providers, one of them has in their ad that it will only take an hour, so far no response from them or the support. Here are the two receipt numbers # 7640 and #11408

**Comment by sweetie77** [comment]
I also ordered zulu watch cost 2400swift but didnt receive any

**Comment by tigor1988** [comment]
me too...
hahaha, lol...

**Comment by lucyho** [comment]
Tiger 1988, what did you order?

**Comment by lucyho** [comment]
On Facebook messenger, no answer. Contact us sends a message, says it’s an email, no answer.i got a comment on Telegram from admin, we don’t control suppliers.. in their notes they have a process for dealing with fraud, but are too busy promoting monetisation.

**Comment by lanngocgioi** [comment]
Tks

Vào 13:17 Th 5, 05 thg 7 2018 Adam Stallard <notifications@github.com> đã
viết:
