### ISSUE TITLE
a whitepaper and that's it? smh

### ISSUE THREAD

**Issue by syncroptician** [swiftdemand/swiftprotocol#17]
Here I was, excited to see github linked – "oh! they actually have proof that they're working on the blockchain!" – and of course, we have a whitepaper as a readme and nothing else. no updates since February.
Happy to help the team however I can, but one must start with _something_...

**Comment by MrXyfir** [comment]
https://github.com/swiftdemand/protocol

**Comment by takeshi12** [comment]
up

**Comment by doenitzkarl77** [comment]
200 million supply is good. Very good.
