### ISSUE TITLE
Good project

### ISSUE THREAD

**Issue by cs3kim** [swiftdemand/swiftprotocol#20]
https://www.swiftdemand.com/?referred_by=cs3kim

**Comment by oiBeNdeRio** [comment]
https://www.swiftdemand.com/?referred_by=bender

2018-06-23 6:00 GMT+03:00 cs3kim <notifications@github.com>:

**Comment by jammai** [comment]
Thank you

0xfd47Cd36AD35eD7D7207c530Bdb250e70Bb9d0C4

**Comment by zub911** [comment]
Ok!
