### ISSUE TITLE
"We Could Not Verify Your Identity Unfortunately we are having trouble verifying your identity. Please contact support for help."

### ISSUE THREAD

**Issue by crypto666** [swiftdemand/swiftprotocol#23]

**Comment by Digital21** [comment]
PLEASE HELP IN A/C VERIFICATION

**Comment by Digital21** [comment]
I'm submitting me E.Mail:samar.chandra56@gmail.com  
#22 Twitter ID: Chandra56Samar        #11 telegram ID -@cryptoc2000.
I request to verify my account.
samar chandra mondal

**Comment by Digital21** [comment]
HI

**Comment by Djnells** [comment]
I think you've got the wrong address

**Comment by crypto666** [comment]
Selfie was approved

**Comment by acong888** [comment]
knapa tak bisa login?
