### ISSUE TITLE
Developer inactivity since 3/2018 dutch auction/ico sale

### ISSUE THREAD

**Issue by CipherOne** [swiftdemand/swiftprotocol#24]
I wonder why the MIA developer/CEO/Founder of SwiftDemand, Christopher Gregorio, hasn't been proactively developing and promoting the SD platform since his dutch auction/ico sale, where he sold 200 million Swifts for between $0.01 USD - $0.15 USD each (ie, $2M-$30m USD and/or the equivalent in Ether), in March of 2018? You'd think that'd be enough to employ a team of developers, have an election for nodes, hire nodes, legal counsel, administrators and PR, not relying a bunch of inexperienced, unpaid volunteers exerting their personal jurisdiction over a virtually abandoned platform you forked from NEO, running on autopilot, needing a plethora of upgrades.

ref: https://s3-us-west-2.amazonaws.com/swiftdemand-production/social_media/SWIFT+TOKEN+SALE+AGREEMENT.pdf

**Comment by Robynpmartin** [comment]
That's very interesting. And it stinks 😣.

**Comment by anaman** [comment]
What is the status of the project development and updates to the network?

**Comment by adamstallard** [comment]
The blockchain is fine.  It has all the changes it needs to run the swiftdemand website--including the regular distribution of Swifts to users.  It doesn't have all of the features in the whitepaper, notably voting--that will come later.

The website code is actively developed. The code for this is in a private repo; it's not open-source.

**Comment by CipherOne** [comment]
As it is way past mid-summer 2108, the website is outdated and needs to be updated.

**Comment by nvrossett** [comment]
@adamstallard Can we consider that the project is not abandoned then?

**Comment by adamstallard** [comment]
> @adamstallard Can we consider that the project is not abandoned then?

Certainly not dead. One of the most active crypto-UBI projects--or crypto projects in general. 19,000 users collected swifts yesterday.

**Comment by adamstallard** [comment]
> As it is way past mid-summer 2108, the website is outdated and needs to be updated.
> Further, AS's reply is not a refutation of what I wrote.

I've refuted you many times, and see no reason to do so again here.  Stop spreading lies about SwiftDemand.

**Comment by CipherOne** [comment]
As there were only 18,714 users that claimed last month, down from over 20K the month before, you're losing users.

**Comment by CipherOne** [comment]
Your rejections were not and are not refutations.

**Comment by anaman** [comment]
> The blockchain is fine. It has all the changes it needs to run the swiftdemand website--including the regular distribution of Swifts to users. It doesn't have all of the features in the whitepaper, notably voting--that will come later.
> 
> The website code is actively developed. The code for this is in a private repo; it's not open-source.

Thanks for the update. Would it be possible to have some pages of the project updated to put an end to the rumours, it would really help even though i understand the source is not opensource.
Sincerely.

**Comment by adamstallard** [comment]
@anaman Good idea.
